breakfast/urls.py
from breakfast import views
from django.urls import path

from breakfast.views import (IndexView,
                             BreakfastListView,
                             ItemDetailView,
                             BreakfastCreateView,
                             BreakfastUpdateView,
                             BreakfastDeleteView,
                             ContactListView,)

app_name = 'breakfast'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('list/', BreakfastListView.as_view(), name='list'),
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('create/', BreakfastCreateView.as_view(), name='create'),
    path('update/<int:pk>/', BreakfastUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BreakfastDeleteView.as_view(), name='delete'),
    path('tag/<slug:tag>/', BreakfastListView.as_view(), name='tag'),
    path('page_list', ContactListView.as_view(), name='page_list'),

    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', views.user_view, name='user'),
    path('other/', views.other_view, name='other'),
    # path('create/', BreakfastFormView.as_view(), name='create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('breakfast.urls')),
    path('admin/', admin.site.urls),
    # path('breakfast/', include('breakfast.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breakfast/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.shortcuts import resolve_url
from django.urls import reverse


class Breakfast(models.Model):
    class Meta:
        ordering = ['-date']

    date = models.DateField(verbose_name='日付', unique=True)
    hours_of_sleep = models.IntegerField(verbose_name='睡眠時間', )
    breakfast = models.CharField(max_length=30, verbose_name='朝ごはん')
    sleep_quality = models.IntegerField(verbose_name='睡眠の質', validators=[MinValueValidator(1), MaxValueValidator(5)])
    feeling = models.IntegerField(verbose_name='今日の気分', validators=[MinValueValidator(1), MaxValueValidator(5)])
    daytime_sleepiness = models.IntegerField(verbose_name='昼間の眠気',
                                             validators=[MinValueValidator(1), MaxValueValidator(5)])
    sweet = models.CharField(max_length=200, blank=True, verbose_name='おやつ')
    memo = models.CharField(max_length=200, blank=True, verbose_name='メモ')  # CharField、TextFieldときはnull=Trueはいらない
    impressions_of_the_day = models.TextField(blank=True, verbose_name='今日の感想')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='カテゴリ')
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='タグ')
    image = models.ImageField(upload_to='images', blank=True, verbose_name='画像')

    def __str__(self):
        return self.date.strftime('%Y/%m/%d')

    def get_feeling_stars(self):  # オブジェクトのメソッドとして呼び出せる、contentに書くとわすれるので、モデルのメソッドにしてそれを呼び出す
        return '★' * self.feeling + '☆' * (5 - self.feeling)

    def get_hours_of_sleep(self):
        return '😴' * self.hours_of_sleep

    def get_sleep_quality(self):
        return '✨' * self.sleep_quality

    def get_daytime_sleepiness(self):
        return '😪' * self.daytime_sleepiness

    def get_absolute_url(self):
        return resolve_url('breakfast:detail', pk=self.pk)  # 戻り値はbreakfastのdetail、adminのモデルの登録画面からサイトを表示できる
        # return reverse('breakfast:detail', kwargs={'pk': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True, )

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True, )
    slug = models.SlugField(max_length=20, unique=True, )

    def __str__(self):
        return f'{self.id}: {self.name}'

breakfast/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Breakfast


class BreakfastModelForm(forms.ModelForm):
    class Meta:
        model = Breakfast
        fields = "__all__"

    def clean_breakfast(self):
        breakfast = self.cleaned_data['breakfast']
        if breakfast == '干し芋':
            raise ValidationError('干し芋はご飯ではなくておやつです！！')
        return breakfast

    def clean(self):
        cleaned_data = super().clean()
        breakfast = cleaned_data.get('breakfast')
        sweet = cleaned_data.get('sweet')

        if breakfast is not None and sweet is not None:
            if breakfast == sweet:
                raise ValidationError('朝食とおやつが一緒なのはどうなのでしょうか？')
            return cleaned_data


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    pass

breakfast/views.py
from datetime import datetime

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import BreakfastModelForm, SignupForm, LoginForm
from .models import Breakfast, Tag


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = SignupForm()

    param = {
        'form': form
    }

    return render(request, 'breakfast/signup.html', param)


def login_view(request):  # ユーザーのログイン
    if request.method == 'POST':
        next = request.POST.get('next')
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()

            if user:
                login(request, user)
                if next == 'None':
                    return redirect('breakfast:index')
                else:
                    return redirect(next)
    else:
        form = LoginForm()
        next = request.GET.get('next')

    param = {
        'form': form,
        'next': next,
    }
    return render(request, 'breakfast/login.html', param)


def logout_view(request):  # ユーザーのログアウト
    logout(request)

    return render(request, 'breakfast/logout.html')


@login_required
def user_view(request):  # ログインユーザーの情報の表示
    user = request.user
    params = {
        'user': user,
    }

    return render(request, 'breakfast/user.html', params)


@login_required
def other_view(request):  # 他のユーザーの情報の表示
    # 現在ログインしているユーザーを除外した全ユーザーをクエリセットとして取得
    users = User.objects.exclude(username=request.user.username)  # excludeは除外

    # 取得したクエリセットをparamsに格納
    params = {
        'users': users,
    }
    return render(request, 'breakfast/other.html', params)


class IndexView(TemplateView):
    template_name = 'breakfast/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = datetime.now().strftime('%Y/%m/%d %H:%M')
        now_hour = datetime.now().hour
        if 5 <= now_hour < 10:
            context['message'] = 'おはようございます'
        elif 10 <= now_hour < 18:
            context['message'] = 'こんにちは'
        else:
            context['message'] = 'こんばんは'
        return context


class BreakfastListView(ListView):
    model = Breakfast
    template_name = 'breakfast/list.html'
    context_object_name = 'breakfast_list'
    paginate_by = 5

    def get_queryset(self):
        qs = Breakfast.objects.order_by('-date')
        search_query = self.request.GET.get('search')
        feeling_query = self.request.GET.get('feeling')
        if search_query and feeling_query:
            qs = qs.filter(breakfast__icontains=search_query, feeling__exact=feeling_query)
        elif search_query:
            qs = qs.filter(breakfast__icontains=search_query)
        elif feeling_query:
            qs = qs.filter(feeling__exact=feeling_query)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.kwargs.get('tag')
        if context['tag']:
            context['tag_queryset'] = Tag.objects.filter(slug=context['tag'])
        else:
            context['tag_queryset'] = Tag.objects.all()
        return context


class ItemDetailView(DetailView):
    model = Breakfast
    template_name = 'breakfast/detail.html'
    context_object_name = 'breakfast'

    def get_queryset(self):
        return Breakfast.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BreakfastCreateView(CreateView):
    template_name = 'breakfast/form.html'
    form_class = BreakfastModelForm
    success_url = reverse_lazy('breakfast:list')


# 成功した時に実行される処理
# def get_success_url(self):
#     messages.success(self.request, '登録しました。')
#     return resolve_url('breakfast:list')


class BreakfastUpdateView(UpdateView):
    template_name = 'breakfast/form.html'
    model = Breakfast
    form_class = BreakfastModelForm
    success_url = reverse_lazy('breakfast:list')

    def get_queryset(self):
        return Breakfast.objects.all()

    def form_valid(self, form):
        messages.success(self.request, '更新しました。')
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url('breakfast:detail', pk=self.kwargs['pk'])


class BreakfastDeleteView(DeleteView):
    template_name = 'breakfast/delete.html'
    model = Breakfast
    success_url = reverse_lazy('breakfast:list')

    def get_queryset(self):
        return Breakfast.objects.all()

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '削除しました。')
        return super().delete(request, *args, **kwargs)


class ContactListView(ListView):
    model = Breakfast
    template_name = 'breakfast/page_list.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/breakfast/base.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    <style>
        .button {
            width: 115px;
            height: 25px;
            background: #8c3dbd;
            padding-left: 20px;
            padding-right: 20px;
            text-align: center;
            text-decoration: none;
            border-radius: 5px;
            color: white;
            font-weight: bold;
            line-height: 25px;
        }

        .button-container {
            display: flex;
            justify-content: flex-start;
        }

        .button-container span {
            width: 80px; /* 適切なサイズに調整してください */
        }


        .button-span {
            display: inline-block;
        }
    </style>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

templates/breakfast/create.html
{% extends "breakfast/base.html" %}
{% block title %}朝ごはんアプリ🍚{% endblock %}

{% block content %}
    <h2>🍚朝ごはん登録🍚</h2>
        <form action="" method="POST">{% csrf_token %}
            <table width="300" height="300">
                {{ form.as_table }}
            </table>
            <p>
                <input type="submit" value = "作成する">
            </p>
        </form>
{% endblock %}

templates/breakfast/delete.html
{% extends "breakfast/base.html" %}

{% block title %}朝ごはんアプリ🍚{% endblock %}

{% block content %}
    <h2>🍚朝ごはん詳細🍚</h2>
    この内容を削除しますか？
    <ul>
        <li>日　　付：{{ breakfast.date }}</li>
        <li>睡眠時間：{{ breakfast.hours_of_sleep }}</li>
        <li>朝ごはん：{{ breakfast.breakfast }}</li>
        <li>睡眠の質：{{ breakfast.sleep_quality }}</li>
        <li>気　　分：{{ breakfast.feeling }}</li>
        <li>お や つ：{{ breakfast.sweet }}</li>
        <li>メ　　モ：{{ breakfast.memo }}</li>
    </ul>

    {% if breakfast.image.file %}
        <img width="200px" height="200px" src="{{ breakfast.image.url }}" alt="{{ breakfast.title }}">
    {% else %}
        <td class="td_image">No image</td>
    {% endif %}


    <form method="post">
        {% csrf_token %}
        <input type="submit" value="削除" class="btn btn-danger"/>


    </form>

{% endblock %}

templates/breakfast/detail.html
{% extends "breakfast/base.html" %}

{% block title %}朝ごはんアプリ🍚{% endblock %}

{% block content %}
    <h2>🍚朝ごはん詳細🍚</h2>
    <ul>
        <li>日　 付 ：{{ breakfast.date }}</li>
        <li>睡眠時間 ：{{ breakfast.get_hours_of_sleep }}</li>
        <li>朝ごはん ：{{ breakfast.breakfast }}</li>
        <li>睡眠の質 ：{{ breakfast.get_sleep_quality }}</li>
        <li>気　　分 ：{{ breakfast.get_feeling_stars }}</li>
        <li>日中の眠気 ：{{ breakfast.get_daytime_sleepiness }}</li>
        <li>お や つ ：{{ breakfast.sweet }}</li>
        <li>メ　　モ ：{{ breakfast.memo }}</li>
        <li>今日の感想：{{ breakfast.impressions_of_the_day }}</li>
        <li>カテゴリ ：{{ breakfast.category }}</li>
        <li>タ　　グ ：
            {% for tag in breakfast.tags.all %}
                <span>{{ tag.name }}&nbsp;</span>
            {% endfor %}
        </li>
    </ul>


    {% if breakfast.image %}
        <img width="250px" height="250px" src="{{ breakfast.image.url }}" alt="{{ breakfast.title }}">
    {% else %}
        <td class="td_image">No image</td>
    {% endif %}


    <div class="button-container">
        <span class="button-span">
            <a class="button" href="{% url 'breakfast:update' pk=breakfast.pk %}">編集</a>
        </span>
        <span></span>
        <span class="button-span">
            <a class="button" href="{% url 'breakfast:delete' pk=breakfast.pk %}">削除</a>
        </span>
        <span></span>
        <span class="button-span">
            <a class="button" href="{% url 'breakfast:list' %}">戻る</a>
        </span>

    </div>

{% endblock %}

templates/breakfast/form.html
{% extends "breakfast/base.html" %}
{% load static %}
{% block title %}朝ごはんアプリ🍚{% endblock %}

{% block content %}
    <h2>🍚朝ごはん登録🍚</h2>
        <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <table width="500" height="300">
                {{ form.as_table }}
            </table>
            <p>
                <input type="submit" value="作成する" class="button">
            </p>
        </form>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

templates/breakfast/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>朝ごはんアプリ🍚</title>
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
            integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
    />
    <style>
        .btn {
            display: inline-block;
            padding: 0.5em 1em;
            text-decoration: none;
            background: #CC99FF;
            color: #FFF;
            border-bottom: solid 4px #627295;
            border-radius: 10px;
            margin: 10px;
            width: 80px;
        }

        .btn:active {
            -webkit-transform: translateY(4px);
            transform: translateY(4px);
            border-bottom: none;
        }

        p {
            text-align: left;
            font-size: 20px;
            font-weight: bold;
            color: #990099;
        }
    </style>
</head>
<body>
<p>
    {{ now }}<br>
    {{ message }} {{ user.username }}さん
</p>
{#<link rel="stylesheet" href="{% static 'breakfast/style.css' %}">#}
<img src="{% static "/breakfast/images/image.png" %}" alt="Dinosaur" width="350" height="500">
<p>
    <button type="button" class="btn btn--orange btn--radius" onclick="location.href={% url 'breakfast:create' %}">
        <i class="fa-solid fa-check"></i> 登録
    </button>
    <button type="button" class="btn btn--orange btn--radius" onclick="location.href={% url 'breakfast:list' %}">
        <i class="fa-regular fa-pen-to-square"></i> 編集
    </button>
</p>
</body>
</html>

templates/breakfast/list.html
{% extends "breakfast/base.html" %}
{% load static %}
{% block title %}朝ごはんアプリ🍚{% endblock %}

{% block content %}
    <h2>🍚朝ごはん一覧🍚</h2>

    <form method="get">
        <label for="search">朝ごはん検索:</label>
        <input type="text" name="search" placeholder="朝ごはん検索...">
        <label for="feeling">今日の気分:</label>
        <select name="feeling" id="feeling">
            <option value="">---</option>
            <option value="1">1 😢</option>
            <option value="2">2 😕</option>
            <option value="3">3 😐</option>
            <option value="4">4 🙂</option>
            <option value="5">5 😃</option>
        </select>
        <button type="submit">検索</button>
    </form>

    {% for item in breakfast_list %}
        <ul>
            <li>
                <a href="{{ item.get_absolute_url }}">🍚</a> {{ item.date }} {{ item.breakfast }} {{ item.impressions_of_the_day }} {{ item.feeling }}
            </li>

        </ul>
    {% endfor %}

    <p>
        タグ検索:&nbsp;
        {% for tag in tag_queryset %}
            {% if tag.slug == tag %}
                <span>{{ tag }}</span>
            {% else %}
                <span><a href="{% url 'breakfast:tag' tag.slug %}">{{ tag }}</a></span>
            {% endif %}
        {% endfor %}
    </p>

    <p><a href="{% url 'breakfast:list' %}">検索解除</a></p>

    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
    {% endif %}

    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <span>{{ num }}</span>
        {% else %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    {% endif %}


    <img src="{% static "/breakfast/images/list.png" %}" alt="Dinosaur">
    <p>
        <span>
            <a class="button" href="{% url 'breakfast:create' %}">登録</a><br>
        </span>
    </p>

{% endblock %}

templates/breakfast/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ログイン</title>
</head>
<body>
    <h1>ログイン</h1>
    <form action="{% url 'breakfast:login' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <p><input type="hidden" name="next" value="{{next}}"></p>
        <p><input type="submit" value="ログイン"></p>
    </form>
</body>
</html>

templates/breakfast/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ログアウト</title>
</head>
<body>
    <p>ログアウトしました。</p>
</body>
</html>

templates/breakfast/other.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>他のユーザー情報</title>
</head>
<body>
    <h1>他のユーザーの情報</h1>
    {% for user in users %}
            <h2>{{ user.username }}</h2>
            <p>連絡先：{{ user.email }}</p>
    {% endfor %}
</body>

templates/breakfast/page_list.html
<h3>🍚朝ごはん一覧🍚</h3>

<div class="pagination">
    {% for item in object_list %}
        <ul>
            <a href="{{ item.get_absolute_url }}">{{ item.date }}</a>
        </ul>
    {% endfor %}
</div>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/breakfast/signup.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ユーザー登録</title>
</head>
<body>
    <h1>ユーザー登録</h1>
    <form action="{% url 'breakfast:signup' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="登録"></p>
    </form>
</body>
</html>

templates/breakfast/user.html
{%  load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>あなたの情報</title>
</head>
<body>
    <h1>{{ user.username }}</h1>
    <p>あなたのメールアドレスは{{ user.email }}です。</p>
    <p>アカウント作成日は{{user.date_joined}}です。</p>
</body>
</html>